### ISSUE TITLE
STL missing for secondary small drive gear

### ISSUE THREAD

**Issue by garyjohnson** [tlalexander/Flutter-Scout#1]
Noticed the STL is missing for the secondary small drive gear. Unfortunately Solidworks is out of my reach, so I can't do it myself. : )

Also it would be great to see if there was an export path to get from the parametric SLDPRT files into something that was editable in a free / cheap tool like 123D Design or Fusion 360 so the community could contribute and fork. Not sure how realistic that is without a full rebuild in a separate program.

**Comment by vinceallenvince** [comment]
I used the one in the V1 folder. I haven't finished printing the Scout and don't know if this is the correct version. But it may be worth a shot if you are further along than me.
https://github.com/tlalexander/Flutter-Scout/blob/master/Scout%20V1/gears/secondary%20small%20drive%20gear.STL

**Comment by sequoia-hope** [comment]
Added it where it should be with d18c20cd94da170de3f17c1c40a759d41630a3ed.
Thanks!
