### ISSUE TITLE
missing 12mm shaft clip

### ISSUE THREAD

**Issue by vinceallenvince** [tlalexander/Flutter-Scout#2]
I can't find the 12 mm shaft clip described in step K of the Make magazine article. I'm guessing it's version 2 of the clip-left-rear-axle found in the V1 shafts folder. However, this clip is too small.

https://github.com/tlalexander/Flutter-Scout/blob/master/Scout%20V1/shafts/clip.%20left%20rear%20axle.STL

**Comment by sequoia-hope** [comment]
Fixed with d18c20cd94da170de3f17c1c40a759d41630a3ed.
Thanks!
